# Generated by Django 4.2 on 2023-05-05 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_alter_student_additional_information_and_more'),
        ('tutors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='tutor_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student.tutorlevel'),
        ),
    ]
