# Generated by Django 4.2 on 2023-05-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0002_alter_tutor_tutor_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='qualification_information',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
