# Generated by Django 4.2 on 2023-05-06 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_remove_student_city_remove_student_country_and_more'),
        ('tutors', '0003_tutor_qualification_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='tutor_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='student.tutorlevel'),
        ),
    ]
