# Generated by Django 4.2 on 2023-05-18 15:45

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0004_alter_tutor_tutor_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
