# Generated by Django 4.2 on 2023-05-25 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0005_tutor_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='qualification_information',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
