# Generated by Django 4.2 on 2023-05-25 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_student_location'),
        ('tutors', '0006_alter_tutor_qualification_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='students_applied',
            field=models.ManyToManyField(to='student.student'),
        ),
    ]
