# Generated by Django 4.2 on 2023-04-27 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0009_alter_student_additional_information_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_rate', models.DecimalField(decimal_places=0, max_digits=2, null=True)),
                ('preferred_gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('NO PREFERENCE', 'NO PREFERENCE')], max_length=50, null=True)),
                ('address', models.CharField(max_length=250, null=True)),
                ('preferred_tutor_level', models.ManyToManyField(to='student.tutorlevel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.subject')),
            ],
        ),
    ]
