# Generated by Django 4.2 on 2023-04-28 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='additional_information',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
    ]
