# Generated by Django 4.2 on 2023-05-01 15:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_assignment_additional_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
