# Generated by Django 4.2 on 2023-05-16 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0004_alter_tutor_tutor_level'),
        ('assignments', '0004_assignment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='tutor',
            field=models.ManyToManyField(blank=True, to='tutors.tutor'),
        ),
    ]
