# Generated by Django 4.2 on 2023-05-16 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0004_alter_tutor_tutor_level'),
        ('assignments', '0005_assignment_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='tutor',
            field=models.ManyToManyField(blank=True, related_name='applied_assignments', to='tutors.tutor'),
        ),
    ]
