# Generated by Django 4.2 on 2023-05-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0006_alter_assignment_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='additional_information',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
