# Generated by Django 4.2 on 2023-04-19 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_subject_remove_student_subjects_student_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='additional_information',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='preferred_gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=50, null=True),
        ),
    ]
