# Generated by Django 4.2 on 2023-04-19 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_longitude_alter_student_preferred_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
