# Generated by Django 4.2 on 2023-04-19 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_student_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
    ]
