# Generated by Django 4.2 on 2023-04-20 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_student_preferred_tutor_level_alter_subject_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='additional_information',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
