# Generated by Django 4.2 on 2023-04-20 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_alter_student_additional_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='additional_information',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='zip_code',
            field=models.CharField(max_length=6),
        ),
    ]
